### ISSUE TITLE
It doesn't Work on android

### ISSUE THREAD

**Issue by Flytreels** [fanchangyong/deershare#65]
u0_a53@localhost ~/d/client (master)> npm start

> client@1.0.0 start
> node scripts/start.js

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /static/js
ℹ ｢wds｣: Content not from webpack is served from /data/data/com.termux/files/home/deershare/client
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:503:5
    at /data/data/com.termux/files/home/deershare/client/node_modules/webpack/lib/NormalModule.js:358:12
    at /data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/data/data/com.termux/files/home/deershare/client/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.3.0

**Comment by Flytreels** [comment]
u0_a53@localhost ~/d/server (master)> npm start

> server@0.0.0 start
> gulp

[23:31:12] Requiring external module @babel/register
[23:31:18] Using gulpfile ~/deershare/server/gulpfile.babel.js
[23:31:18] Starting 'default'...
[23:31:18] Starting 'envDev'...
[23:31:19] Finished 'envDev' after 8.9 ms
[23:31:19] Starting 'server'...
[23:31:19] Finished 'server' after 335 ms
[23:31:19] Finished 'default' after 368 ms
[23:31:19] [nodemon] 2.0.16
[23:31:19] [nodemon] to restart at any time, enter `rs`
[23:31:19] [nodemon] watching path(s): **/*
[23:31:19] [nodemon] watching extensions: js,json
[23:31:19] [nodemon] starting `node src/index.js`
Listening on port 3001
Starting prerender
2022-06-12T15:31:33.925Z Starting Prerender
2022-06-12T15:31:33.931Z Starting Chrome
2022-06-12T15:31:33.938Z unable to find Chrome install. Please specify with chromeLocation
2022-06-12T15:31:33.946Z Prerender server accepting requests on port 3999
2022-06-12T15:31:33.948Z undefined
2022-06-12T15:31:33.959Z Failed to start and/or connect to Chrome. Please make sure Chrome is running
2022-06-12T15:31:33.961Z Stopping Chrome
[23:31:34] [nodemon] clean exit - waiting for changes before restart
